### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [rotb4rt/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``

https://github.com/rotb4rt/prj-rev-bwfs-dasmoto/blob/f7453ba095f67df060043e75150fc8af15eda2f4/Dasmotos/index.html#L5

**Comment by rotb4rt** [comment]
changed in h1 and title
