### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by martoio** [rotb4rt/prj-rev-bwfs-dasmoto#2]
Good job on separating the HTML into sections! One thing you might want to consider is changing the ``<div>`` into a ``<section>`` to improve the semantics of your code.
If you aren't familiar with semantic HTML: http://www.hongkiat.com/blog/html-5-semantics/
Example:
```
<!-- First section -->
<section> <!-- or <div>, but <section> is more semantic -->
 <h2 class="brushes">Brushes</h2>
 <img src="#" alt="#" />
 <h3>Text</h3>
 <p>
  Lorem <span class="price">ipsum</span>
 </p>
</section>
```
https://github.com/rotb4rt/prj-rev-bwfs-dasmoto/blob/f7453ba095f67df060043e75150fc8af15eda2f4/Dasmotos/index.html#L11-L17

**Comment by rotb4rt** [comment]
I have changed the <div> to a <section>. Thanks! I am looking forward to implement more semantic code from the article you send!
