### ISSUE TITLE
File paths

### ISSUE THREAD

**Issue by martoio** [rotb4rt/prj-rev-bwfs-dasmoto#4]
Don't use absolute paths. I don't have this path on my computer, so it won't work when I download your project. Use relative file paths.

https://www.kirupa.com/html5/all_about_file_paths.htm
https://github.com/rotb4rt/prj-rev-bwfs-dasmoto/blob/f7453ba095f67df060043e75150fc8af15eda2f4/Dasmotos/resources/css/style.css#L9

**Comment by rotb4rt** [comment]
background-image: url("../images/pattern.jpeg");
